### ISSUE TITLE
[Question] Are there plans for a python version of this book?

### ISSUE THREAD

**Issue by simkimsia** [software-tools-in-javascript/stjs#25]

**Comment by gvwilson** [comment]
I originally planned to do this in Python, but I wanted to learn JavaScript myself, and this seemed like a good way to do that. If you or someone else would like to translate what we have into Python, please let me know.

**Comment by simkimsia** [comment]
Do you have any issues if I give it a shot at a pace of spending 15 mins a day?

**Comment by gvwilson** [comment]
Of course not - that would be wonderful. Please send me a link to your repo, and if I may make a suggestion, please don't worry about writing full sentences or about following the structure of the existing examples exactly:

1.  Point-form nodes in an `index.md` Markdown file in each lesson's sub-directory while you're working on code is a lot easier to edit (turning those notes into full paragraphs once you're sure of what you want to say is easy).
2. 
2.  The natural way to do things in Python will be different than the JavaScript way. For example, I expect the two chapters on systems programming and asynchronous programming will become one chapter in Python because callbacks aren't used nearly as often (thankfully).

cheers,
Greg

**Comment by simkimsia** [comment]
> Please send me a link to your repo

I did that and slightly more by following your instructions in the README.md of this repo and email you

Thank you
